version: '3.1'

services:

  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: nginx-sample
    volumes:
      - "./conf.d:/etc/nginx/conf.d"
      - "./html:/usr/share/nginx/html"
      - "./app:/usr/share/nginx/app"

    ports:
      - "8099:80"
    tty: true
    # command: sh -c "service nginx restart"
